geekshop/adminapp/urls.py
from django.urls import re_path

from adminapp.views import users, categories, products
from adminapp.controllers import user, categori, product

app_name = 'adminapp'

urlpatterns = [
    re_path(r'^users/index/$', user.UserListView.as_view(), name='users_index'),
    re_path(r'^users/create/$', user.UserCreateView.as_view(), name='users_create'),
    re_path(r'^users/update/(?P<pk>\d+)/$', user.UserUpdateView.as_view(), name='users_update'),
    re_path(r'^users/delete/(?P<pk>\d+)/$', users.delete, name='users_delete'),

    # categories (CRUD)
    re_path(r'^categories/create/$', categori.ProductCategoryCreateView.as_view(), name='category_create'),
    re_path(r'^categories/read/$', categories.categories, name='categories'),
    re_path(r'^categories/update/(?P<pk>\d+)/$', categori.ProductCategoryUpdateView.as_view(), name='category_update'),
    re_path(r'^categories/delete/(?P<pk>\d+)/$', categori.ProductCategoryDeleteView.as_view(), name='category_delete'),

    re_path(r'^products/create/category/<(?P<pk>\d+)/$', products.product_create, name='product_create'),
    re_path(r'^products/read/category/(?P<pk>\d+)/$', products.products, name='products'),
    re_path(r'^products/read/(?P<pk>\d+)/$', product.ProductDetailView.as_view(), name='product_read'),
    re_path(r'^products/update/(?P<pk>\d+)/$', products.product_update, name='product_update'),
    re_path(r'^products/delete/(?P<pk>\d+)/$', products.product_delete, name='product_delete'),
]

geekshop/authapp/urls.py
from django.urls import re_path
import authapp.views as authapp

import authapp.views as controller

app_name = 'authapp'

urlpatterns = [
    # path('', controller.login, name='index'),
    re_path(r'^$', controller.redirect_to_login, name='index'),
    re_path(r'^login/$', controller.login, name='login'),
    re_path(r'^logout/$', controller.logout, name='logout'),

    re_path(r'^register/$', controller.register, name='register'),
    re_path(r'^edit/$', controller.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', controller.verify, name='verify'),

]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as controller
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.urls import re_path

urlpatterns = [
    re_path(r'^$', controller.index),
    re_path(r'^index/', controller.index, name='index'),
    re_path(r'^contakt/', controller.contakt, name='contakt'),
    re_path(r'^goods1/', controller.goods1, name='goods1'),

    re_path(r'^catalog/', include('mainapp.urls', namespace='catalog')),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),

    re_path(r'^admin/', include('adminapp.urls', namespace='admin')),
    # path('admin-django/', admin.site.urls),
    re_path(r'^', include('social_django.urls', namespace='social')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/adminapp/models/categories.py
from django import forms
from mainapp.models import ProductCategory


class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProductCategoryEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

geekshop/adminapp/models/products.py
from django import forms
from mainapp.models import Product


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProductEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

geekshop/adminapp/models/users.py
from authapp.models import ShopUser
from authapp.forms import UpdateForm


class ShopUserAdminEditForm(UpdateForm):
    class Meta:
        model = ShopUser
        fields = '__all__'

geekshop/adminapp/controllers/categori.py
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse_lazy
from django.shortcuts import HttpResponseRedirect
from mainapp.models import ProductCategory


class ProductCategoryReadView(ListView):
    model = ProductCategory
    template_name = 'adminapp/categories/read.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/categories/update.html'
    success_url = reverse_lazy('admin:categories')
    fields = '__all__'


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/categories/update.html'
    success_url = reverse_lazy('admin:categories')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории/редактирование'

        return context


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/categories/delete.html'
    success_url = reverse_lazy('admin:categories')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())

geekshop/adminapp/controllers/product.py
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse_lazy
from django.shortcuts import HttpResponseRedirect
from mainapp.models import Product

class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/products/products_read.html'

geekshop/adminapp/controllers/user.py
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse_lazy
from django.shortcuts import HttpResponseRedirect
from authapp.models import ShopUser


class UserListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users/users_index.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(UserListView, self).dispatch(request, *args, **kwargs)


class UserCreateView(CreateView):
    model = ShopUser
    template_name = 'adminapp/users/update.html'
    fields = ('username', 'age', 'password', 'email', 'first_name', 'avatar')
    success_url = reverse_lazy('admin:users_index')


class UserUpdateView(UpdateView):
    model = ShopUser
    template_name = 'adminapp/users/update.html'
    fields = ('username', 'age', 'email', 'first_name', 'avatar')
    success_url = reverse_lazy('admin:users_index')

    def get_context_data(self, **kwargs):
        parent_context = super(UserUpdateView, self).get_context_data(**kwargs)
        parent_context['title'] = 'пользователи/создание'

        return parent_context


class UserDeleteView(DeleteView):
    model = ShopUser
    template_name = 'adminapp/users/delete.html'
    success_url = reverse_lazy('admin:users_index')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object() #получаем пользователя
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())

geekshop/adminapp/views/categories.py
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, HttpResponseRedirect, reverse, get_object_or_404
from mainapp.models import ProductCategory
from adminapp.models.categories import ProductCategoryEditForm


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    title = 'админка/категории'

    categories_list = ProductCategory.objects.all()

    content = {
        'title': title,
        'objects': categories_list
    }

    return render(request, 'adminapp/categories/read.html', content)


@user_passes_test(lambda u: u.is_superuser)
def category_create(request):
    title = 'категории/создание'

    if request.method == 'POST':
        category_form = ProductCategoryEditForm(request.POST, request.FILES)
        if category_form.is_valid():
            category_form.save()
            return HttpResponseRedirect(reverse('admin:categories'))
    else:
        category_form = ProductCategoryEditForm()

    content = {'title': title, 'update_form': category_form}

    return render(request, 'adminapp/categories/update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def category_update(request, pk):
    title = 'категории/редактирование'

    edit_category = get_object_or_404(ProductCategory, pk=pk)
    if request.method == 'POST':
        edit_form = ProductCategoryEditForm(request.POST, request.FILES, instance=edit_category)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:category_update', args=[edit_category.pk]))
    else:
        edit_form = ProductCategoryEditForm(instance=edit_category)

    content = {'title': title, 'update_form': edit_form}

    return render(request, 'adminapp/categories/update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def category_delete(request, pk):
    title = 'категории/удаление'

    category = get_object_or_404(ProductCategory, pk=pk)

    if request.method == 'POST':
        category.is_active = False
        category.save()
        return HttpResponseRedirect(reverse('admin:categories'))

    content = {'title': title, 'category_to_delete': category}

    return render(request, 'adminapp/categories/delete.html', content)

geekshop/adminapp/views/products.py
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, HttpResponseRedirect, reverse, get_object_or_404
from mainapp.models import ProductCategory, Product
from adminapp.models.products import ProductEditForm
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.db import connection


@user_passes_test(lambda u: u.is_superuser)
def products(request, pk):
    title = 'админка/продукт'

    category = get_object_or_404(ProductCategory, pk=pk)
    products_list = Product.objects.filter(productcategory__pk=pk).order_by('name')

    content = {
        'title': title,
        'category': category,
        'objects': products_list,
    }

    return render(request, 'adminapp/products/priducts_index.html', content)


# def product_read(request, pk):
#     title = 'продукт/подробнее'
#
#     product = get_object_or_404(Product, pk=pk)
#
#     content = {'title': title, 'object': product, }
#
#     return render(request, 'adminapp/product_read.html', content)


def product_create(request, pk):
    title = 'продукт/создание'
    category = get_object_or_404(ProductCategory, pk=pk)

    if request.method == 'POST':
        product_form = ProductEditForm(request.POST, request.FILES)
        if product_form.is_valid():
            product_form.save()
            return HttpResponseRedirect(reverse('admin:products', args=[pk]))
    else:
        # задаем начальное значение категории в форме
        product_form = ProductEditForm(initial={'category': category})

    content = {'title': title, 'update_form': product_form, 'category': category}

    return render(request, 'adminapp/products/update.html', content)


def product_update(request, pk):
    title = 'продукт/редактирование'

    edit_product = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        edit_form = ProductEditForm(request.POST, request.FILES, instance=edit_product)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:products', args=[edit_product.pk]))
    else:
        edit_form = ProductEditForm(instance=edit_product)

    content = {'title': title, 'update_form': edit_form, 'category': edit_product.productcategory}

    return render(request, 'adminapp/products/update.html', content)


def product_delete(request, pk):
    title = 'продукт/удаление'

    product = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        product.is_active = False
        product.save()
        return HttpResponseRedirect(reverse('admin:products', args=[product.productcategory.pk]))

    content = {
        'title': title,
        'product_to_delete': product
    }

    return render(request, 'adminapp/products/delete.html', content)


def db_profile_by_type(prefix, type, queries):
    update_queries = list(filter(lambda x: type in x['sql'], queries))
    print(f'db_profile {type} for {prefix}:')
    [print(query['sql']) for query in update_queries]

geekshop/adminapp/views/users.py
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, reverse
from authapp.models import ShopUser
from django.contrib.auth.decorators import user_passes_test
from authapp.forms import RegisterForm
from adminapp.models.users import UpdateForm


@user_passes_test(lambda user: user.is_superuser)
def index(request):
    users_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')
    title = 'Пользователи'

    return render(request, 'adminapp/users/users_index.html', {
        'objects': users_list,
        'title': title,
    })


@user_passes_test(lambda user: user.is_superuser)
def create(request):
    title = 'пользователи/создание'

    if request.method == 'POST':
        user_form = RegisterForm(request.POST, request.FILES)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('admin:users'))
    else:
        user_form = RegisterForm()

    content = {'title': title, 'update_form': user_form}

    return render(request, 'adminapp/users/update.html', content)


@user_passes_test(lambda user: user.is_superuser)
def update(request, pk):
    title = 'пользователи/редактирование'

    edit_user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        edit_form = UpdateForm(request.POST, request.FILES, instance=edit_user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:user_update', args=[edit_user.pk]))
    else:
        edit_form = UpdateForm(instance=edit_user)

    content = {'title': title, 'update_form': edit_form}

    return render(request, 'adminapp/users/update.html', content)


@user_passes_test(lambda user: user.is_superuser)
def delete(request, pk):
    title = 'пользователи/удаление'

    user = get_object_or_404(ShopUser, pk=pk)

    if request.method == 'POST':
        user.is_active = False
        user.save()
        return HttpResponseRedirect(reverse('admin:users_index'))

    content = {
        'title': title,
        'user_to_delete': user
    }

    return render(request, 'adminapp/users/delete.html', content)

geekshop/adminapp/templates/adminapp/products/delete.html
{% extends 'adminapp/layout_categories.html' %}

{% load staticfiles %}


{% block content %}
    <div class="product_delete">
        Уверены, что хотите удалить продукт <strong>{{ product_to_delete.name }}</strong>?
        <form action="{% url 'admin:product_delete' product_to_delete.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:products' product_to_delete.productcategory.pk %}">
                отмена
            </a>
        </button>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/products/priducts_index.html
{% extends 'adminapp/layout_categories.html' %}

{% load staticfiles %}


{% block content %}
    <div class="products_list">
        <a href={% url 'admin:product_create' category.pk %}>новый продукт</a>


        {% for object in objects %}
            <div class="product_record {% if not object.is_active %}not_active{% endif %}">
                <img src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}"
                     width="200px">
                <div class="product_name">
                    {{ object.name|title }}
                </div>
                <div class="product_actions">
                    <li class="link_menu"><a href={% url 'admin:product_read' object.pk %}>подробнее</a>

                        <a href={% url 'admin:product_update' object.pk %}>редактировать</a>

                        <a href={% url 'admin:product_delete' object.pk %}>удалить</a></li>


                </div>
                <div class="summary">
                    <b>цена</b>
                    <p>{{ object.price }} руб</p>
                    <b>количество</b>
                    <p>{{ object.quantity }}</p>
                </div>
                <div class="product_desc">
                    {{ object.short_desc|title }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/products/products_read.html
{% extends 'adminapp/layout_categories.html' %}

{% load staticfiles %}


{% block content %}
    <div class="product_read">
        <div class="product_name">
            Продукт<strong>{{ object.category.name|title }} / {{ object.name|title }}</strong>
        </div>
        <img src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}" width="200px">
        <div class="summary">
            <b>цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество</b>
            <p>{{ object.quantity }}</p>
            <b>в каталоге</b>
            <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
            <p>
                <button>
                    <a href={% url 'admin:product_update' object.pk %}>редактировать</a>
                </button>
            </p>
            <p>
                <button>
                    <a href={% url 'admin:product_delete' object.pk %}>удалить</a>
                </button>
            </p>
            <p>
                <button>
                    <a href={% url 'admin:products' object.productcategory.pk %}>назад</a>
                </button>
            </p>
        </div>
        <div class="product_desc">
            <b>краткая информация</b>
            <p>
                {{ object.short_desc }}
            </p>
            <br>
            <br>
            <b>подробная информация</b>
            <p>
                {{ object.description }}
            </p>
        </div>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/products/update.html
{% extends 'adminapp/layout_categories.html' %}

{% load staticfiles %}


{% block content %}
    <div class="new_category_form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ update_form.as_p }}
            <input type="submit" value="сохранить">
        </form>
        <button class="btn btn-round form-control last">
            <a href="{% url 'admin:products' category.pk %}">
                к списку продуктов
            </a>
        </button>
    </div>
{% endblock %}