geekshop/authapp/urls.py
from django.urls import re_path
import authapp.views as authapp

import authapp.views as controller

app_name = 'authapp'

urlpatterns = [
    # path('', controller.login, name='index'),
    re_path(r'^$', controller.redirect_to_login, name='index'),
    re_path(r'^login/$', controller.login, name='login'),
    re_path(r'^logout/$', controller.logout, name='logout'),

    re_path(r'^register/$', controller.register, name='register'),
    re_path(r'^edit/$', controller.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', controller.verify, name='verify'),

]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as controller
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.urls import re_path

urlpatterns = [
    re_path(r'^$', controller.index),
    re_path(r'^index/', controller.index, name='index'),
    re_path(r'^contakt/', controller.contakt, name='contakt'),
    re_path(r'^goods1/', controller.goods1, name='goods1'),

    re_path(r'^catalog/', include('mainapp.urls', namespace='catalog')),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),

    re_path(r'^admin/', include('adminapp.urls', namespace='admin')),
    # path('admin-django/', admin.site.urls),
    re_path(r'^', include('social_django.urls', namespace='social')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.urls import re_path
from django.views.decorators.cache import cache_page

import mainapp.views as controller

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', controller.catalog, name='index'),
    re_path(r'^category/page/(?P<page>\d+)/$', controller.catalog, name='page'),
    re_path(r'^category/(?P<pk>\d+)/ajax/$',
            cache_page(3600)(controller.catalog_ajax)),
    re_path(r'^category/(?P<pk>\d+)/page/(?P<page>\d+)/ajax/$',
            cache_page(3600)(controller.catalog_ajax)),
    re_path(r'^product/(?P<pk>\d+)/$', controller.catalog, name='productcategory'),
    re_path(r'^details/(?P<pk>\d+)/$', controller.product_detail, name='details'),

]

geekshop/mainapp/models.py
from django.db import models


# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=30, verbose_name='Название')
    logo = models.ImageField(upload_to='departments', verbose_name='Логотип', blank=True)


class Person(models.Model):
    name = models.CharField(max_length=30, verbose_name='Имя')
    last_name = models.CharField(max_length=30, verbose_name='Фамилия')
    age = models.PositiveIntegerField(verbose_name='Возраст', default=0)
    image = models.ImageField(upload_to='users_images', blank=True)

    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} {self.last_name} {self.department.name}"


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=64)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return f"{self.name}"


class Product(models.Model):
    name = models.CharField(max_length=30, verbose_name='Имя')
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(db_index=True, verbose_name='активна', default=True)

    productcategory = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, related_name='products')

    def __str__(self):
        return f"{self.name} {self.productcategory.name}"

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('productcategory', 'name')

geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpRequest
from .models import ProductCategory, Product
from basketapp.models import Basket
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings
from django.core.cache import cache

from django.template.loader import render_to_string
from django.views.decorators.cache import cache_page
from django.http import JsonResponse
from django.views.decorators.cache import never_cache


# Create your views here.
def index(request: HttpRequest):
    title = 'Главная'

    products = Product.objects.filter(is_active=True, productcategory__is_active=True).select_related('productcategory')

    return render(request, 'mainapp/layouts/layouts.html', {
        'title': title,
        'data': products

    })


@cache_page(3600)
def catalog(request: HttpRequest, pk=None, page=1):
    title = 'Каталог'
    product = ProductCategory.objects.all()

    if pk is not None:
        products = Product.objects.filter(productcategory__pk=pk)
    else:
        products = Product.objects.all()

    provider = Paginator(products, 1)

    try:
        products_provider = provider.page(page)
    except PageNotAnInteger:
        products_provider = provider.page(1)
    except EmptyPage:
        products_provider = provider.page(provider.num_pages)

    return render(request, 'mainapp/layouts/layouts1.html', {
        'title': title,
        'provider': products_provider,
        'productcategory': product,
    })


def catalog_ajax(request: HttpRequest, pk=None, page=1):
    title = 'Каталог'
    product = ProductCategory.objects.all()

    if pk is not None:
        products = Product.objects.filter(productcategory__pk=pk)
    else:
        products = Product.objects.all()

    provider = Paginator(products, 1)

    try:
        products_provider = provider.page(page)
    except PageNotAnInteger:
        products_provider = provider.page(1)
    except EmptyPage:
        products_provider = provider.page(provider.num_pages)

    content = {
        'title': title,
        'provider': products_provider,
        'productcategory': product,
    }

    result = render_to_string('mainapp/includes/inc_products_list_content.html',
                              context=content,
                              request=request)

    return JsonResponse({'result': result})


def contakt(request: HttpRequest):
    title = 'Контакты'

    return render(request, 'mainapp/layouts/layouts2.html', {
        'title': title,

    })


def goods1(request: HttpRequest):
    title = 'Товар'

    return render(request, 'mainapp/layouts/layouts3.html', {
        'title': title,

    })


def product_detail(request: HttpRequest, pk=None):
    if id is not None:
        # details = Product.objects.get(pk=id)
        details = get_object_or_404(Product, pk=pk)
        products = Product.objects.filter(productcategory__pk=details.productcategory_id)
        product = ProductCategory.objects.all()

    context = {
        'title': f'Товар: {details.name}',
        'product': product,
        'details': details,
        'products': products,
    }

    return render(request, 'mainapp/details.html', context)


def get_current_user(current_user):
    if current_user.is_authenticated:
        basket = Basket.objects.filter(user=current_user)
    else:
        basket = None

    return basket


def load_from_json(file_name):
    with open(os.path.join(JSON_PATH, file_name + '.json'), 'r',
              errors='ignore') as infile:
        return json.load(infile)


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True,
                                              category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True,
                                      category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_orederd_by_price():
    if settings.LOW_CACHE:
        key = 'products_orederd_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True,
                                              category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True,
                                      category__is_active=True).order_by('price')


def get_products_in_category_orederd_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_orederd_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True,
                                              category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True,
                                      category__is_active=True).order_by('price')

geekshop/mainapp/templates/mainapp/layouts/layouts.html
{% extends 'mainapp/index.html' %}

{% load static %}

{% block menu %}

{% include "mainapp/widgets/menu.html" %}

{% endblock %}


{% block content %}

<div class="conteiner">
    <p>Добро подаловать в магазин медицинского оборудования DOCTMENT. У нас всегда только самое лучшее и
        проверенное оборудование.</p>
    <hr>
</div>

{% endblock %}

{% block js %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
{% endblock %}

geekshop/mainapp/templates/mainapp/layouts/layouts1.html
{% extends 'mainapp/catalog.html' %}

{% load static %}

{% block menu %}

    {% include "mainapp/widgets/menu.html" %}

{% endblock %}

{% block content %}
    <div class="conteiner">

        <h1>Категории товаров</h1>
        {% include "mainapp/widgets/menu_cataloga.html" %}
        <ul class="link_menu">
            {% if provider.has_previous %}
                <li class="menu">
                    <a href="{% url 'catalog:page' page=provider.previous_page_number %}">Prev</a>
                </li>
            {% endif %}
            <li class="menu">
                <p>page {{ provider.number }} of {{ provider.paginator.num_pages }}</p>
            </li>
            {% if provider.has_next %}
                <li class="menu">
                    <a href="{% url 'catalog:page' page=provider.next_page_number %}">Next</a>
                </li>
            {% endif %}
        </ul>
        <ul class="link_menu">
            {% for products in provider %}
                <div class="product-box padding-site">
                    <a href="{% url 'catalog:details' pk=products.id %}">
                        <div class="linia">
                            <img src="{{ MEDIA_URL }}{{ products.image }}" width="200" height="200"
                                 alt="{{ products.short_desc }}">
                            <div class="noname">
                                <h3 class="nona">{{ products.productcategory.name }}</h3>
                                <p class="non">{{ products.name }}</p>
                                <p class="non">{{ products.description }}</p>
                                <p class="non">Стоит {{ products.price }}</p>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/layouts/layouts2.html
{% extends 'mainapp/contakt.html' %}

{% load static %}

{% block menu %}

{% include "mainapp/widgets/menu.html" %}

{% endblock %}


{% block content %}
<div class="conteiner">

    <form action="#">
        <h1>Напишите нам:</h1>
        Имя <input class="cupre" type="text" placeholder="Илья"><br>
        Email <input class="cupre" type="email" placeholder="Hi@mail.ru"><br>
        Тема <input class="cupre" type="text" placeholder="У меня есть вопрос"><br>
        Если у вас есть вопрос, напишит его сюда пожалуйста <br> <textarea class="text"></textarea><br>
        <button type="submit">Отправить</button>
        <button type="reset">Удалить</button>
    </form>
    <h3>Адрес</h3>
    <p>Наш номер телефона: 89999999999</p>
    <p>Наш адрес: г.Москва, мкр.Беговой, ул.Самаяновая, дом 30</p>
    <p>Наша почта: Novaya@mail.ru</p>
    <script type="text/javascript" charset="utf-8" async
            src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A9444049044d51d9b1304e01c6bf334936f17efbf6177ac4109e39a6cefca7041&amp;width=100%&amp;height=400&amp;lang=ru_RU&amp;scroll=true"></script>
    <hr>
</div>
{% endblock %}
{% block js %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
{% endblock %}

geekshop/mainapp/templates/mainapp/layouts/layouts3.html
{% extends 'mainapp/goods1.html' %}

{% load static %}

{% block menu %}

{% include "mainapp/widgets/menu.html" %}

{% endblock %}


{% block content %}

<div class="conteiner">

        <h1>Медицинский цветной монитор Sony LMD-2110MD</h1>
        <h2 class="zagolovki">Описание товара</h2>
        <div class="od">
            <a href="{% static 'Images/пробник.jpg' %}" target="_blank"> <img class="img1" src="{% static 'Images/пробник.jpg' %}"></a>
            <p class="cratkoe">Медицинский цветной монитор Sony LMD-2110MD&nbsp;&mdash; это новая модель оборудования, которая может служить как в&nbsp;качестве вспомогательного монитора в&nbsp;кабинете, так и&nbsp;полноценным профессиональным вариантом бюджетного оборудования.</p>
        </div>

        <h2 class="zagolovki">Характеристика товара</h2>
        <table>
            <tr>
                <td rowspan="2">Тип: ЖК дисплей с активной матрицей a-Si TFT <br> Разрешение: 1920 x 1080 пикселей (Full HD)</td>
                <td>Угол обзора (спецификация ЖК-панели): 170°/160° (типовое значение) (по горизонтали/вертикали, контрастность >10:1)</td>
                <td>Эффективный размер изображения (В х Ш) (по диагонали): 477 x 268 мм, 547 мм</td>
            </tr>
            <tr>
                <td colspan="2">Количество цветов: Приблизительно 16,7 миллионов цветов</td>
            </tr>
        </table>
        <ol>
            <li class="menu-two">Монитор имеет стандартные размеры: 515,3мм.</li>
            <li class="menu-two">Вес оборудования сподставкой 8,6кг.</li>
            <li class="menu-two">Отдельный вес монитора 6,9кг.</li>
            <li class="menu-two">Производитель: SONY.</li>
            <li class="menu-two">Оборудование реализуется сбазовой комплектацией.</li>
            <li class="menu-two">В составе присутствует кабель, руководство, монитор, фиксатор, СД-РОМ.</li>
        </ol>
        <h2 class="zagolovki">Подробное описание товара</h2>
        <p class="podrobnoe">Оснащен матрицей a-Si TFT с&nbsp;покрытием АР.<br> Разрешение&nbsp;&mdash; 1920&nbsp;на 1080, при этом размер картинки 477&times;280.<br> Вход сигнала цифровой: HD, S-Videos, компонентный.<br> Присутствует композитный видеосигнал и&nbsp;коннектор внешнего сигнала (для 1x&nbsp;BNC).<br> Контрастность&nbsp;10:1, угол обзора по&nbsp;вертикали 160&nbsp;градусов, по&nbsp;горизонтали&nbsp;&mdash; 180.<br> Стереогнездо размером 3, 5&nbsp;мм.<br> D-Sub 9&nbsp;пин для BKM-341HS (HD/SD-SDI).<br> Есть разъемы для дистанционного управления, встроенный громкоговоритель, а&nbsp;также параллельный порт.</p>
        <h2 class="zagolovki">Преимущества монитора Sony LMD-2110MD</h2>
        <p class="podrobnoe">Есть возможность выбрать предустановки гамма.<br> Вариативность интерфейсов, видео и&nbsp;звукового сигналов.<br> Наличие опционального адаптера под разные типы входов.<br> Большой выбор вариантов отражения экрана.<br> Наличие международных сертификатов качества&nbsp;&mdash; EN&nbsp;60601-1, CSA C22.2 No.601-1, UL&nbsp;60601-1.</p>
      <a class="buy" href="{% url 'contakt' %}">Купить</a>
        <hr></div>

{% endblock %}

{% block js %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
{% endblock %}