geekshop/adminapp/urls.py
from django.urls import re_path

from adminapp.views import users, categories, products
from adminapp.controllers import user, categori, product

app_name = 'adminapp'

urlpatterns = [
    re_path(r'^users/index/$', user.UserListView.as_view(), name='users_index'),
    re_path(r'^users/create/$', user.UserCreateView.as_view(), name='users_create'),
    re_path(r'^users/update/(?P<pk>\d+)/$', user.UserUpdateView.as_view(), name='users_update'),
    re_path(r'^users/delete/(?P<pk>\d+)/$', users.delete, name='users_delete'),

    # categories (CRUD)
    re_path(r'^categories/create/$', categori.ProductCategoryCreateView.as_view(), name='category_create'),
    re_path(r'^categories/read/$', categories.categories, name='categories'),
    re_path(r'^categories/update/(?P<pk>\d+)/$', categori.ProductCategoryUpdateView.as_view(), name='category_update'),
    re_path(r'^categories/delete/(?P<pk>\d+)/$', categori.ProductCategoryDeleteView.as_view(), name='category_delete'),

    re_path(r'^products/create/category/<(?P<pk>\d+)/$', products.product_create, name='product_create'),
    re_path(r'^products/read/category/(?P<pk>\d+)/$', products.products, name='products'),
    re_path(r'^products/read/(?P<pk>\d+)/$', product.ProductDetailView.as_view(), name='product_read'),
    re_path(r'^products/update/(?P<pk>\d+)/$', products.product_update, name='product_update'),
    re_path(r'^products/delete/(?P<pk>\d+)/$', products.product_delete, name='product_delete'),
]

geekshop/authapp/urls.py
from django.urls import re_path
import authapp.views as authapp

import authapp.views as controller

app_name = 'authapp'

urlpatterns = [
    # path('', controller.login, name='index'),
    re_path(r'^$', controller.redirect_to_login, name='index'),
    re_path(r'^login/$', controller.login, name='login'),
    re_path(r'^logout/$', controller.logout, name='logout'),

    re_path(r'^register/$', controller.register, name='register'),
    re_path(r'^edit/$', controller.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', controller.verify, name='verify'),

]

geekshop/basketapp/urls.py
from django.urls import re_path

import basketapp.views as controller

app_name = 'basketapp'

urlpatterns = [
    re_path(r'^$', controller.index, name='index'),
    re_path(r'^add/(?P<pk>\d+)/$', controller.add, name='add'),
    re_path(r'^remove/(?P<pk>\d+)/$', controller.remove, name='remove'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as controller
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.urls import re_path

urlpatterns = [
    re_path(r'^$', controller.index),
    re_path(r'^index/', controller.index, name='index'),
    re_path(r'^contakt/', controller.contakt, name='contakt'),
    re_path(r'^goods1/', controller.goods1, name='goods1'),

    re_path(r'^catalog/', include('mainapp.urls', namespace='catalog')),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),

    re_path(r'^admin/', include('adminapp.urls', namespace='admin')),
    # path('admin-django/', admin.site.urls),
    re_path(r'^', include('social_django.urls', namespace='social')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.urls import re_path
from django.views.decorators.cache import cache_page

import mainapp.views as controller

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', controller.catalog, name='index'),
    re_path(r'^category/page/(?P<page>\d+)/$', controller.catalog, name='page'),
    re_path(r'^category/(?P<pk>\d+)/ajax/$',
            cache_page(3600)(controller.catalog_ajax)),
    re_path(r'^category/(?P<pk>\d+)/page/(?P<page>\d+)/ajax/$',
            cache_page(3600)(controller.catalog_ajax)),
    re_path(r'^product/(?P<pk>\d+)/$', controller.catalog, name='productcategory'),
    re_path(r'^details/(?P<pk>\d+)/$', controller.product_detail, name='details'),

]

geekshop/ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path

app_name = "ordersapp"

urlpatterns = [
    re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
    re_path(r'^forming/complete/(?P<pk>\d+)/$',
            ordersapp.order_forming_complete, name='order_forming_complete'),
    re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(),
            name='order_create'),
    re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(),
            name='order_read'),
    re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(),
            name='order_update'),
    re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(),
            name='order_delete'),
    re_path(r'^product/(?P<pk>\d+)/price/$', ordersapp.get_product_price)
]

geekshop/mainapp/models.py
from django.db import models


# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=30, verbose_name='Название')
    logo = models.ImageField(upload_to='departments', verbose_name='Логотип', blank=True)


class Person(models.Model):
    name = models.CharField(max_length=30, verbose_name='Имя')
    last_name = models.CharField(max_length=30, verbose_name='Фамилия')
    age = models.PositiveIntegerField(verbose_name='Возраст', default=0)
    image = models.ImageField(upload_to='users_images', blank=True)

    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} {self.last_name} {self.department.name}"


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=64)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return f"{self.name}"


class Product(models.Model):
    name = models.CharField(max_length=30, verbose_name='Имя')
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(db_index=True, verbose_name='активна', default=True)

    productcategory = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, related_name='products')

    def __str__(self):
        return f"{self.name} {self.productcategory.name}"

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('productcategory', 'name')

geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpRequest
from .models import ProductCategory, Product
from basketapp.models import Basket
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings
from django.core.cache import cache

from django.template.loader import render_to_string
from django.views.decorators.cache import cache_page
from django.http import JsonResponse
from django.views.decorators.cache import never_cache


# Create your views here.
def index(request: HttpRequest):
    title = 'Главная'

    products = Product.objects.filter(is_active=True, productcategory__is_active=True).select_related('productcategory')

    return render(request, 'mainapp/layouts/layouts.html', {
        'title': title,
        'data': products

    })


@cache_page(3600)
def catalog(request: HttpRequest, pk=None, page=1):
    title = 'Каталог'
    product = ProductCategory.objects.all()

    if pk is not None:
        products = Product.objects.filter(productcategory__pk=pk)
    else:
        products = Product.objects.all()

    provider = Paginator(products, 1)

    try:
        products_provider = provider.page(page)
    except PageNotAnInteger:
        products_provider = provider.page(1)
    except EmptyPage:
        products_provider = provider.page(provider.num_pages)

    return render(request, 'mainapp/layouts/layouts1.html', {
        'title': title,
        'provider': products_provider,
        'productcategory': product,
    })


def catalog_ajax(request: HttpRequest, pk=None, page=1):
    title = 'Каталог'
    product = ProductCategory.objects.all()

    if pk is not None:
        products = Product.objects.filter(productcategory__pk=pk)
    else:
        products = Product.objects.all()

    provider = Paginator(products, 1)

    try:
        products_provider = provider.page(page)
    except PageNotAnInteger:
        products_provider = provider.page(1)
    except EmptyPage:
        products_provider = provider.page(provider.num_pages)

    content = {
        'title': title,
        'provider': products_provider,
        'productcategory': product,
    }

    result = render_to_string('mainapp/includes/inc_products_list_content.html',
                              context=content,
                              request=request)

    return JsonResponse({'result': result})


def contakt(request: HttpRequest):
    title = 'Контакты'

    return render(request, 'mainapp/layouts/layouts2.html', {
        'title': title,

    })


def goods1(request: HttpRequest):
    title = 'Товар'

    return render(request, 'mainapp/layouts/layouts3.html', {
        'title': title,

    })


def product_detail(request: HttpRequest, pk=None):
    if id is not None:
        # details = Product.objects.get(pk=id)
        details = get_object_or_404(Product, pk=pk)
        products = Product.objects.filter(productcategory__pk=details.productcategory_id)
        product = ProductCategory.objects.all()

    context = {
        'title': f'Товар: {details.name}',
        'product': product,
        'details': details,
        'products': products,
    }

    return render(request, 'mainapp/details.html', context)


def get_current_user(current_user):
    if current_user.is_authenticated:
        basket = Basket.objects.filter(user=current_user)
    else:
        basket = None

    return basket


def load_from_json(file_name):
    with open(os.path.join(JSON_PATH, file_name + '.json'), 'r',
              errors='ignore') as infile:
        return json.load(infile)


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True,
                                              category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True,
                                      category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_orederd_by_price():
    if settings.LOW_CACHE:
        key = 'products_orederd_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True,
                                              category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True,
                                      category__is_active=True).order_by('price')


def get_products_in_category_orederd_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_orederd_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True,
                                              category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True,
                                      category__is_active=True).order_by('price')

geekshop/mainapp/templates/mainapp/widgets/inc_products_list_content.html
{% load staticfiles %}

{% block content %}
   <div class="conteiner">

            <h1>{{ details.name }}</h1>
            <h2 class="zagolovki">Описание товара</h2>
            <div class="od">
                <a href="{{ MEDIA_URL }}{{ details.image }}" target="_blank"> <img class="img1" src="
                        {{ MEDIA_URL }}{{ details.image }}" width="200 "></a>
                <p class="cratkoe">{{ details.description }}</p>
                <p class="cratkoe"> Стоит {{ details.price | rubles }}</p>
            </div>

            {#            {% if request.user.is_authenticated %}#}

            <a class="buy" href="{% url 'basket:add' pk=details.id %}">Купить</a>

            {#            {% endif %}#}


            <hr>
        </div>

        <ul class="link_menu">
            {% for products in products %}
                <div class="product-box padding-site">
                    <a href="{% url 'catalog:details' pk=products.id %}">
                        <div class="linia">
                            <img src="{{ MEDIA_URL }}{{ products.image }}" width="200"
                                 alt="{{ products.short_desc }}">
                            <div class="noname">
                                <h3 class="nona">{{ products.productcategory.name }}</h3>
                                <p class="non">{{ products.name }}</p>
                                <p class="non">{{ products.description }}</p>
                                <p class="non">{{ products.price }}</p>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </ul>
{% endblock %}

geekshop/mainapp/templates/mainapp/widgets/menu.html
{% load static %}

<header>

    <div class="headerr">

        <a href="{% url 'index' %}"><img src="{% static 'Images/logomak_logo.png' %}" alt="Logo" width="250"></a>

        <ul class="spiski">
            <li><a class="menu" href="{% url 'index' %}">Главная</a></li>
            <li><a class="menu" href="{% url 'catalog:index' %}">Каталог</a></li>
            <li><a class="menu" href="{% url 'contakt' %}">Контакты</a></li>
            <li><a class="menu" href="{% url 'basket:index' %}">Корзина
                {% if basket %}{{ basket.0.total_quantity }} товаров {{ basket.0.total_cost }} руб. {% endif %}</a>
            </li>

            {% if user.is_authenticated %}
                <li>
                    <div class="dropdown">
                        <a class="dropdown-toggle" href="" data-toggle="dropdown">
                            {{ user.first_name|default:'Пользователь' }}
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'auth:edit' %}">
                                    профиль
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'ordersapp:orders_list' %}">
                                    заказы
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
            {% endif %}


            {% if user.is_superuser %}
                <li>
                    <a class="menu" href="{% url 'admin:categories' %}">
                        Админ-панель
                    </a>
                </li>
            {% endif %}


            <li>
                {% if user.is_authenticated %}
                    <a class="menu" href="{% url 'auth:logout' %}">
                        Выйти
                    </a>
                {% else %}
                    <a class="menu" href="{% url 'auth:login' %}">
                        Войти
                    </a>
                {% endif %}
            </li>


        </ul>
    </div>


</header>

geekshop/mainapp/templates/mainapp/widgets/menu_cataloga.html
<ul class="link_menu">
    {% for product in productcategory %}
        <li class="menu"><a href="{% url 'catalog:productcategory' product.pk %}">{{ product.name }}</a></li>
    {% endfor %}
</ul>